<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Imports" data-toc-modified-id="Imports-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Imports</a></span></li><li><span><a href="#Universal-function" data-toc-modified-id="Universal-function-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Universal function</a></span></li><li><span><a href="#A-subtle-difference" data-toc-modified-id="A-subtle-difference-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>A subtle difference</a></span></li><li><span><a href="#References" data-toc-modified-id="References-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>References</a></span></li><li><span><a href="#Requirements" data-toc-modified-id="Requirements-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Requirements</a></span></li></ul></div>

# Introduction
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-warning">
<font color=black>

**What?** Universal function

</font>
</div>

# Imports
<hr style = "border:2px solid black" ></hr>

In [27]:
import numpy as np  
import math

# Universal function
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-info">
<font color=black>

- They are “universal” in the sense that they in general operate on ndarray objects as well as on basic Python data types. 
- However, when applying universal functions to, say, a Python float object, one needs to be aware of the reduced performance compared to the same functionality found in the `math` module.

</font>
</div>

In [2]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])  
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [3]:
type(a)  

numpy.ndarray

In [4]:
a = np.array(['a', 'b', 'c'])  
a

array(['a', 'b', 'c'], dtype='<U1')

In [5]:
a = np.arange(2, 20, 2)  
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
a = np.arange(8, dtype=float)  
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [7]:
a[5:]  

array([5., 6., 7.])

In [8]:
a[:2]  

array([0., 1.])

In [9]:
a.sum()  

28.0

In [10]:
a.std()  

2.29128784747792

In [11]:
a.cumsum()  

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [12]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l  

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [13]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [14]:
2 * a  

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [15]:
a ** 2  

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [16]:
2 ** a  

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [17]:
a ** a  

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [18]:
np.exp(a)  

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [19]:
np.sqrt(a)  

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [20]:
np.sqrt(2.5)  

1.5811388300841898

In [22]:
math.sqrt(2.5)  

1.5811388300841898

In [24]:
%timeit np.sqrt(2.5)  

949 ns ± 10.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
%timeit math.sqrt(2.5)  

105 ns ± 0.375 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# A subtle difference
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-info">
<font color=black>

- In these micro-benchmarks, math.sqrt will be slower, because of the slight time it takes to lookup the sqrt in the math namespace. You can improve it slightly with: `from math import sqrt`

</font>
</div> 

# References
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-warning">
<font color=black>

- https://github.com/yhilpisch/py4fi2nd/blob/master/code/ch04/04_numpy.ipynb

</font>
</div>

# Requirements
<hr style = "border:2px solid black" ></hr>

In [29]:
%load_ext watermark
%watermark -v -iv

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Python implementation: CPython
Python version       : 3.9.7
IPython version      : 7.29.0

json    : 2.0.9
autopep8: 1.6.0
numpy   : 1.22.2

