<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#What-is-numpy?" data-toc-modified-id="What-is-numpy?-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>What is <code>numpy</code>?</a></span></li><li><span><a href="#Vectorization" data-toc-modified-id="Vectorization-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Vectorization</a></span></li><li><span><a href="#Conclusions" data-toc-modified-id="Conclusions-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Conclusions</a></span></li><li><span><a href="#References" data-toc-modified-id="References-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>References</a></span></li><li><span><a href="#Requirements" data-toc-modified-id="Requirements-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Requirements</a></span></li></ul></div>

# Introduction
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-warning">
<font color=black>

**What?** Vectorisation

</font>
</div>

# What is `numpy`?
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-info">
<font color=black>

- `NumPy` provides a multidimensional array object to:
    - store homogeneous data arrays
    - store heterogeneous data arrays
    - supports vectorization of codes

</font>
</div>

# Vectorization
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-info">
<font color=black>

- The fundamental idea is to conduct an operation to a complex object **at once** and not by looping over the single elements of the object.
- Functional programming tools such as `map()` and `filter()` provide some basic means for vectorization. However, NumPy has vectorization built in deep down in its core.
    
</font>
</div>

In [129]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))  
s = np.arange(12).reshape((4, 3)) * 0.5  

In [130]:
r  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [131]:
s  

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [132]:
r + s  

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [133]:
r + 3  

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [134]:
2 * r  

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [135]:
2 * r + 3  

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [136]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [137]:
r.shape

(4, 3)

In [138]:
s = np.arange(0, 12, 4)  
s  

array([0, 4, 8])

In [139]:
r + s  

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [140]:
s = np.arange(0, 12, 3)  
s  

array([0, 3, 6, 9])

In [141]:
# causes intentional error
# r + s  

In [142]:
r.transpose() + s  

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [143]:
sr = s.reshape(-1, 1)  
sr

array([[0],
       [3],
       [6],
       [9]])

In [144]:
sr.shape  

(4, 1)

In [145]:
r + s.reshape(-1, 1)  

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [146]:
def f(x):
    return 3 * x + 5  

In [147]:
f(0.5)  

6.5

In [148]:
f(r)  

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

# Conclusions
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-danger">
<font color=black>

-  What NumPy does is to simply apply the function f to the object element-wise. 
- In that sense, by using this kind of operation one does not avoid loops; one only avoids them on the Python level and **delegates** the looping to NumPy. 
- On the NumPy level, looping over the ndarray object is taken care of by optimized code, most of it written in C and therefore generally faster than pure Python. 
    
</font>
</div>

# References
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-warning">
<font color=black>

- https://github.com/yhilpisch/py4fi2nd/blob/master/code/ch04/04_numpy.ipynb
- Hilpisch, Yves. Python for finance: mastering data-driven finance. O'Reilly Media, 2018.

</font>
</div>

# Requirements
<hr style = "border:2px solid black" ></hr>

In [ ]:
%load_ext watermark
%watermark -v -iv